Culture specific bugs are fixed. All tests are "green" now.
iwate/ODataHttpClient pull request #7
Opened 2019-06-21 16:41 UTC by psmolich79

Fixed problems related to culture and proper conversions.

2019-07-26 04:55 UTC, iwate commented
Hi @psmolich79  ! Thank you for your contribute!

I check your code and it looks good :)

However, I want to know what values cause error.

Would you add a few test cases specific values ?

2021-08-04 16:47 UTC, bxbxbx commented
Hi @iwate please consider to merge this pull request, as it fixes formatting problems on non english systems.
The source of the problems is that the actual culture is used in the parameterizers, which leads to problems with floating point numbers on non english systems.

2021-08-05 06:58 UTC, iwate commented on src/ODataHttpClient/Models/Request.cs
> +                //content = body.ToString();
This need plain text, so we cannot use json serializer.

2021-08-05 07:30 UTC, iwate commented
@bxbxbx Thank you for your comments.

I understand this current culture issue but I cannot merge this PR because this patch has a many changes from current master.

I've added red pattern  test codes for this issue. If @psmolich79 modify and recreate this PR, I merge it.

When this PR is not update until next weekend, I create a patch by self and close this PR.

https://github.com/iwate/ODataHttpClient/commit/597337a80d4b00be997eca4198f390be2e9b9e9e

2021-08-06 08:33 UTC, psmolich79 commented
> @bxbxbx Thank you for your comments.
> 
> I understand this current culture issue but I cannot merge this PR because this patch has a many changes from current master.
> 
> I've added red pattern test codes for this issue. ([597337a](https://github.com/iwate/ODataHttpClient/commit/597337a80d4b00be997eca4198f390be2e9b9e9e)) If @psmolich79 could modify and recreate this PR, I merge it.
> 
> When this PR is not update until next weekend, I create a patch by self and close this PR.

Hi. There are too many changes due to my habit of cleaning the code with Resharper :) Sorry about that. At the beginning, I didn't plan to ask for merge of my changes. I'll try to sort it out and make only a minimal amount of changes this weekend.

2021-08-06 13:38 UTC, psmolich79 commented
Hi @iwate . Please check if this pull request can be integrated now.

2021-08-06 14:19 UTC, iwate requested changes
@psmolich79 Thank you modify PR. 

However, this change includes a change that reverts to the old code.

Could you re-create it including only your changes?

If it is difficult, you can create new a branch from current master and create new a PR.

2021-08-06 14:19 UTC, iwate commented on src/ODataHttpClient/Models/Request.cs
> +                content = serializer.Serialize<T>(body);
This request content type is needed plain text whichi cannnot use serializer. use `ToString` with CultureInfo.InvariantCulture.

2021-08-06 14:19 UTC, iwate commented on src/ODataHttpClient/Models/Response.cs
> -        public string Body { get => GetStringFromUTF8(Binary); }
GetStringFromUTF8 is needed for BOM

2021-08-06 16:31 UTC, closed without merging

2021-08-07 00:52 UTC, iwate commented
This issue is resolved at #24